### ISSUE TITLE
I do not get list channel and not read stream. because connection timeout

### ISSUE THREAD

**Issue by fabri8bit** [braice/MuMuDVB#108]
Problem description:

http://pastebin.com/VsQng3wg

help me?

**Comment by fabri8bit** [comment]
the cause is the weak signal?

**Comment by braice** [comment]
Hello,

You have to wait the end of the autoconfiguration to get the channel list,
so wait a minute or so.

Otherwise the unicast socket could be tied to a wrong interface.

Regards

2015-12-29 11:44 GMT-05:00 fabri8bit notifications@github.com:

**Comment by updateshencore** [comment]
I waited two days. The browser page is still waiting for a connection. The problem is the frequency freq = 698,000 on Mux Mediaset ITALIA. The new test:  http://pastebin.com/PjM7hbsi

....
Mon Jan 18 12:45:28 2016:Main: :18217:Channel "Rete4" down.Card 0
Mon Jan 18 12:45:28 2016:Main: :18217:Channel "Mediaset On Demand" down.Card 0
Mon Jan 18 12:45:28 2016:Main: :18217:Channel "Infinity" down.Card 0
Mon Jan 18 12:45:29 2016:Main: :18217:Channel "Canale5" down.Card 0
Mon Jan 18 12:45:29 2016:Main: :18217:Channel "Italia1" down.Card 0
Mon Jan 18 12:45:29 2016:Main: :18217:Channel "La 5" down.Card 0
Mon Jan 18 12:45:29 2016:Main: :18217:Channel "TGCOM24" down.Card 0
Mon Jan 18 12:45:29 2016:Main: :18217:Channel "Iris" down.Card 0

....

**Comment by fabri8bit** [comment]
I waited two days. The browser page is still waiting for a connection. The problem is the frequency freq = 698,000 on Mux Mediaset ITALIA. The new test: http://pastebin.com/PjM7hbsi

....
Mon Jan 18 12:45:28 2016:Main: :18217:Channel "Rete4" down.Card 0
Mon Jan 18 12:45:28 2016:Main: :18217:Channel "Mediaset On Demand" down.Card 0
Mon Jan 18 12:45:28 2016:Main: :18217:Channel "Infinity" down.Card 0
Mon Jan 18 12:45:29 2016:Main: :18217:Channel "Canale5" down.Card 0
Mon Jan 18 12:45:29 2016:Main: :18217:Channel "Italia1" down.Card 0
Mon Jan 18 12:45:29 2016:Main: :18217:Channel "La 5" down.Card 0
Mon Jan 18 12:45:29 2016:Main: :18217:Channel "TGCOM24" down.Card 0
Mon Jan 18 12:45:29 2016:Main: :18217:Channel "Iris" down.Card 0

....

**Comment by m0yellow** [comment]
I checked your log,
it seems mumudvb tries to set a filter, then the device stops sending data.
Could you please upload a minute of -dumpstream ? 
Could you please test with only one channel configured, maybe with sid_list (check doku)?
If that works, please increase the number of channels until it breaks again.
Do you have another device to verify against? maybe even another model, or another firmware?

Chasing this kind of bug between driver, mumudvb and maybe broken stream is hard, but you had a good start.
btw: maximum wait time can still be measured in minutes, not hours ;)
