### ISSUE TITLE
Is MuMudvb Still active + decrypt issue new Oscam

### ISSUE THREAD

**Issue by nightshadow36** [braice/MuMuDVB#128]
Hello.
Love the software but have a few issues.
1: Is MuMudvb still active will there be a version above 2.0?
2: Is version 2.0 better than 1.7.3 or is 1.7.3 the most stable? Uptime is important.
3: MuMudvb is not working with new Oscam versions above r11200 any reason?

Thank you.

**Comment by braice** [comment]
Hello

1 yes but there is more maintenance than new features as of today
2 the auto configuration was greatly improved as well as internals for
packets analysis. it leads to a better following of channel changes and
more robustness
3 the person who developed the oscam support didn't updated the code from
some time and I don't have the equipment to test and try to fix it.any help
is of course very welcome

Best

Brice

**Comment by yo2loj** [comment]
I checked the current oscam r11273 setup, found the following issues and fixed it to a working state.
1 - oscam sends a CA_SET_PID with -1 for the needed CA PID after the PMT sending.
This will get the channel>ca_idx__refcnt to -1, which will prevent any further CA_SET_PID acceptance for this channel
2 - thec camd socket will tend to overrun on reception, so instead of getting the needed 13 bytes packet of a CA_SET_PID, (the first one is -1) it will also get the beginning of the next one, thus desynchronizing the PID settings. This does not happen always, but most of the time.

Patch tested with oscam r11273 and 20 concurrent decrypts on one transponder and it works as expected.

Patch file for scam_getcw.c in mumudvb v2 solving both issues attached.
Pull request  #130 created.

[scam_getcw.zip](https://github.com/braice/MuMuDVB/files/440627/scam_getcw.zip)

**Comment by yo2loj** [comment]
Just an update: tested with 20 concurrent decrypts on one transponder and it works as expected.

**Comment by nightshadow36** [comment]
@yo2loj Thank you for the patch for MuMudvb to work. May I ask a question, how do i apply the patch? Is it to MuMudvb or to Oscam & how to apply the patch is it a case of copy and paste or to i add it to oscam simple build? Thank you for your time

**Comment by yo2loj** [comment]
Just unpack the scam_getcw.diff file to your mumudvb src folder and do
`patch scam_getcw.c scam_getcw.diff`
This will update your c file. You can delete the diff file afterwards.
Then do the usual make on mumudvb...

**Comment by nightshadow36** [comment]
Thank you J

**Comment by nightshadow36** [comment]
@yo2loj 
Thank you very much for this. I was posting on many forums for about 3 months with no replies.
You have made my day. All is working.
Thank you. :)

**Comment by yo2loj** [comment]
Removed a redundant PID check left over by mistake in the patch (Commited in #130).
This has no functional impact, just it should not be there.

**Comment by nightshadow36** [comment]
Has the patch been uploaded again, should i reapply the patch again to to remove the pid check?
Thank you.

**Comment by yo2loj** [comment]
No, the patch has not changed, just the pull request. Don't worry about it.
As I said, it has no functional impact. Probably the compiler will optimize it away...

**Comment by braice** [comment]
Hello

I just merged the pull request,

Thank you very much

Brice

**Comment by yo2loj** [comment]
@nightshadow36 Could you please close this issue as solved.
Thank you.
