### ISSUE TITLE
Tutorial: how to build for Android?

### ISSUE THREAD

**Issue by bluepuma77** [braice/MuMuDVB#129]
So far I have been playing around with the Raspberry (pure Linux), which is a nice tinkering solution but kind of awkward when it comes to DVB, because the USB power is too weak, so you always need a powered USB hub with a second power supply and so on...

Hardware evolves at an incredible speed and today you get powerful Android boxes for as little money as $30 including remote and power supply - and some of them supply enough USB power for a DVB USB dongle. If you read [CNXSoft](http://www.cnx-software.com/) it seems a new box is coming to market every week.

With so many Android boxes on the market, is there a tutorial available on how to build MuMuDVB for Android? Written for noobs that have not compiled anything for Android before?

**Comment by m0yellow** [comment]
As mumudvb is for streaming, it would be difficult to write a how to document, since there wouldn't be any interface available on the box, besides adb shell.

If you would think of using the embedded DVB Tuner as streaming tuner, it would be perfect to find a box that runs any form of embedded linux, or android with enough linux tools installed to be called linux. 
The DVB Tuner needs to be exposed as a linux device (usually linked to /dev/dvb/) for mumudvb to use it. Android (which?) could have it only exposed to the Android API.

But all STBs I know do not deliver enough developer information to call it a SDK. And this information differs from box to box.
