### ISSUE TITLE
Can descramble only 4 tuners

### ISSUE THREAD

**Issue by vladojko** [braice/MuMuDVB#150]
Hi,

I have 8 tuners in my system, 4 x TBS 6902 cards.
Mumudvb can decode channels from 4 tuners simultaneously, but when i start 5th process descrambling does not work. I recompiled oscam and increased number of demultiplexers to 128, so that is not the issue. there must be something else preventing 5th mumudvb process to connect to oscam and start decoding..

i am attaching debug log

[mumudvb.txt](https://github.com/braice/MuMuDVB/files/672162/mumudvb.txt)

**Comment by vladojko** [comment]
and i discovered after 4 tuners are active, if i start one more oscam process i am able to decode channels from 4 more tuners.

There must be something in oscam that is preventing mumudvb processes to get access to the socket file /tmp/camd.socket

I am even thinking to start multiple oscam processes with different socket file, but neither oscam or mumudvb have configuration option to set socket file. Maybe I would need to change code and recompile...

**Comment by braice** [comment]
Hello

I don't know the oscam code, but maybe you can have a look to how it
handles the camd socket
http://stackoverflow.com/questions/670891/is-there-a-way-for-multiple-processes-to-share-a-listening-socket

Look in the file
https://github.com/gfto/oscam/blob/2780c48789c8e1427df4078ea9b06e0b51594bbc/module-dvbapi.c
in function dvbapi_init_listenfd
There is a max queue of 5, maybe this is where the issue is

I will be happy to add the results of your investigation in the FAQ

Brice

2016-12-27 11:38 GMT-05:00 vladojko <notifications@github.com>:

**Comment by braice** [comment]
Oscam related issue, if I can do anything in MuMuDVB, please reopen
