### ISSUE TITLE
this open source project not maintained？

### ISSUE THREAD

**Issue by taojishou** [braice/MuMuDVB#255]

**Comment by braice** [comment]
It is

Just its quite mature so frequency is low

**Comment by taojishou** [comment]
can i give you a TS file, Can you help me to read it? Mumudvb does not work…

**Comment by tonyapton** [comment]
such a shame you dont answer many peoples problems lately. mumudvb has been wonderfull for me in DVB-S2 situations but i am now having problems with DVB-T2.
you often comment that the driver issued by the manufacturer is commonly the problem but I have a question about why wont mumudvb tune to T2 when "kaffiene" has no problem doing so...... the driver must work for them so why not you?
I do accept that Kaffeine can choose which frontend to use in the cheap Astrometa T2 usb stick  but when I try to select the frontend 1 with all the bells and whistles mumudvb can select the thing just doesnt behave properly...... also I am finding thet mumudvb freezes, or if it does tune the channels "drop" out...  I have also noticed it jam packs the 1GB local lan so much that i cant access internet at same time???
please help... thanks

**Comment by braice** [comment]
Hello

From your last sentence it looks like your LAN is not properly configured
for multicast. that might be one of the reason of the weird behavior you
are experiencing.
You can either try to run mumudvb in unicast (less stable than multicast)
or set up your switches so it manages multicast properly.

If you can tune with another software it might be because of non support of
auto bandwidth or similar auto parameters.
In that case can you share mumudvb configuration as well as the other
software configuration ?

Brice

**Comment by malakudi** [comment]
No response since Februray, issue can be closed.
